### ISSUE TITLE
turntable motor enabled on startup

### ISSUE THREAD

**Issue by dlarue** [mariolukas/FabScanPi-Firmware#2]
I've had a few issues with the rPi2 software and was surprised, and almost burned, when I got back to the machine after an hour or so and found the turntable motor too hot to touch.

Seems like powering up and maybe a timeout should prevent the motors from being enabled for too long.

**Comment by mariolukas** [comment]
Mhh i thought that it is fixed in the current firmware version. I added code for deactivating to the server part too. Maybe i missed some parts in code.

**Comment by dlarue** [comment]
I recall you doing that too. But let me check my firmware version to be sure I have the latest just to make sure I didn't skip the update.  Looking at the latest, I see the Sanguinololu changes to configuration.h but interestingly the VERSION is still dated 2015 so I'm not sure how to check the installed code.  I'll have to make certain to upload the latest firmware and recheck motor enable. I'll also look at the code to make sure that on Setup() the motors are disabled so that without an rPi and FabScanPi server connected the motors are disabled.

**Comment by mariolukas** [comment]
I am not using pololu drivers in my primary fabscan setup. The silent step stick drivers can handle enable/disable over time by themselves (idle mode). Tomorrow i will get the a prototype of the new case. Then i will have a third setup, in which i will use pololu drivers to test those behaviours.
